# Generated by Django 3.2 on 2021-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0002_topichome2'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/set/'),
        ),
    ]
