# Generated by Django 2.2.4 on 2019-08-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/cover/'),
        ),
    ]
