# Generated by Django 2.2.4 on 2019-08-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0005_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
