# Generated by Django 2.2.4 on 2019-08-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0007_auto_20190815_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
    ]
