# Generated by Django 2.2.4 on 2019-08-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0009_auto_20190815_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/set/'),
        ),
    ]
