# Generated by Django 2.2.4 on 2019-08-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0010_auto_20190815_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
