# Generated by Django 3.0.6 on 2020-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0012_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
