# Generated by Django 3.0.6 on 2020-05-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0014_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='urllink',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
