# Generated by Django 3.0.6 on 2021-04-18 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0019_booktwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booktwo',
        ),
    ]
