# Generated by Django 3.0.6 on 2021-05-01 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0020_delete_booktwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topicpost',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topicpost',
            name='text',
        ),
    ]
