# Generated by Django 3.0.6 on 2021-05-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0021_auto_20210501_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpost',
            name='date_added',
        ),
    ]
